version: "3"
services:

  auth:
    build:
      dockerfile: Dockerfile
      context: ./auth
    container_name: auth
    ports:
      - "8004:8004"
    restart: always
    volumes:
      - .:/app
      - /app/auth/node_modules

    env_file:
      - ./auth/.env.dev

  branch:
    build:
      dockerfile: Dockerfile
      context: ./branch
    container_name: branch
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - .:/app
      - /app/branch/node_modules
    env_file:
      - ./branch/.env.dev

  user:
    build:
      dockerfile: Dockerfile
      context: ./user
    container_name: user
    ports:
      - "8002:8002"
    restart: always
    volumes:
      - .:/app/
      - /app/user/node_modules
    env_file:
      - ./user/.env.dev
